// All 50 US state highpoints. locationId matches the location entry in locations-data.js if visited.
export default [
  { state: "Alabama",        name: "Cheaha Mountain",    elevation: 2413,  locationId: "cheaha-mountain" },
  { state: "Alaska",         name: "Denali",             elevation: 20310, locationId: null },
  { state: "Arizona",        name: "Humphreys Peak",     elevation: 12633, locationId: "humphreys-peak" },
  { state: "Arkansas",       name: "Magazine Mountain",  elevation: 2753,  locationId: null },
  { state: "California",     name: "Mt. Whitney",        elevation: 14505, locationId: "mt-whitney" },
  { state: "Colorado",       name: "Mt. Elbert",         elevation: 14440, locationId: "mt-elbert" },
  { state: "Connecticut",    name: "Mt. Frissell",       elevation: 2380,  locationId: "mt-frissell" },
  { state: "Delaware",       name: "Ebright Azimuth",    elevation: 448,   locationId: "ebright-azimuth" },
  { state: "Florida",        name: "Britton Hill",       elevation: 345,   locationId: "britton-hill" },
  { state: "Georgia",        name: "Brasstown Bald",     elevation: 4784,  locationId: "brasstown-bald" },
  { state: "Hawaii",         name: "Mauna Kea",          elevation: 13796, locationId: null },
  { state: "Idaho",          name: "Borah Peak",         elevation: 12662, locationId: "borah-peak" },
  { state: "Illinois",       name: "Charles Mound",      elevation: 1235,  locationId: null },
  { state: "Indiana",        name: "Hoosier Hill",       elevation: 1257,  locationId: "hoosier-hill" },
  { state: "Iowa",           name: "Hawkeye Point",      elevation: 1670,  locationId: null },
  { state: "Kansas",         name: "Mt. Sunflower",      elevation: 4039,  locationId: "mt-sunflower" },
  { state: "Kentucky",       name: "Black Mountain",     elevation: 4145,  locationId: "black-mountain" },
  { state: "Louisiana",      name: "Driskill Mountain",  elevation: 535,   locationId: null },
  { state: "Maine",          name: "Mt. Katahdin",       elevation: 5268,  locationId: null },
  { state: "Maryland",       name: "Backbone Mountain",  elevation: 3360,  locationId: "backbone-mountain" },
  { state: "Massachusetts",  name: "Mt. Greylock",       elevation: 3491,  locationId: "mt-greylock" },
  { state: "Michigan",       name: "Mt. Arvon",          elevation: 1979,  locationId: null },
  { state: "Minnesota",      name: "Eagle Mountain",     elevation: 2301,  locationId: null },
  { state: "Mississippi",    name: "Woodall Mountain",   elevation: 806,   locationId: null },
  { state: "Missouri",       name: "Taum Sauk Mountain", elevation: 1772,  locationId: null },
  { state: "Montana",        name: "Granite Peak",       elevation: 12807, locationId: null },
  { state: "Nebraska",       name: "Panorama Point",     elevation: 5424,  locationId: "panorama-point" },
  { state: "Nevada",         name: "Boundary Peak",      elevation: 13147, locationId: null },
  { state: "New Hampshire",  name: "Mt. Washington",     elevation: 6288,  locationId: null },
  { state: "New Jersey",     name: "High Point",         elevation: 1803,  locationId: "high-point" },
  { state: "New Mexico",     name: "Wheeler Peak",       elevation: 13161, locationId: "wheeler-peak" },
  { state: "New York",       name: "Mt. Marcy",          elevation: 5344,  locationId: null },
  { state: "North Carolina", name: "Mt. Mitchell",       elevation: 6684,  locationId: "mt-mitchell" },
  { state: "North Dakota",   name: "White Butte",        elevation: 3506,  locationId: null },
  { state: "Ohio",           name: "Campbell Hill",      elevation: 1549,  locationId: "campbell-hill" },
  { state: "Oklahoma",       name: "Black Mesa",         elevation: 4973,  locationId: "black-mesa" },
  { state: "Oregon",         name: "Mt. Hood",           elevation: 11249, locationId: null },
  { state: "Pennsylvania",   name: "Mt. Davis",          elevation: 3213,  locationId: "mt-davis" },
  { state: "Rhode Island",   name: "Jerimoth Hill",      elevation: 812,   locationId: "jerimoth-hill" },
  { state: "South Carolina", name: "Sassafras Mountain", elevation: 3553,  locationId: "sassafras-mountain" },
  { state: "South Dakota",   name: "Black Elk Peak",     elevation: 7244,  locationId: null },
  { state: "Tennessee",      name: "Clingmans Dome",     elevation: 6643,  locationId: "clingmans-dome" },
  { state: "Texas",          name: "Guadalupe Peak",     elevation: 8751,  locationId: "guadalupe-peak" },
  { state: "Utah",           name: "Kings Peak",         elevation: 13528, locationId: null },
  { state: "Vermont",        name: "Mt. Mansfield",      elevation: 4393,  locationId: null },
  { state: "Virginia",       name: "Mt. Rogers",         elevation: 5729,  locationId: "mt-rogers" },
  { state: "Washington",     name: "Mt. Rainier",        elevation: 14411, locationId: null },
  { state: "West Virginia",  name: "Spruce Knob",        elevation: 4863,  locationId: "spruce-knob" },
  { state: "Wisconsin",      name: "Timms Hill",         elevation: 1951,  locationId: null },
  { state: "Wyoming",        name: "Gannett Peak",       elevation: 13809, locationId: null },
];
