$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $repoRoot

$root = "Pictures"
$extensions = @(".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif", ".svg")

$files = Get-ChildItem -Path $root -Recurse -File |
  Where-Object { $extensions -contains $_.Extension.ToLowerInvariant() }

$groups = $files | Group-Object DirectoryName | Sort-Object Name

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Auto-generated by scripts/generate-gallery-manifest.ps1")
$lines.Add("const galleryManifest = {")

foreach ($group in $groups) {
  $dir = ($group.Name -replace "\\", "/")
  $dirRel = $dir.Substring($dir.IndexOf("Pictures"))
  $lines.Add('  "' + $dirRel + '": [')

  foreach ($file in ($group.Group | Sort-Object Name)) {
    $path = ($file.FullName -replace "\\", "/")
    $rel = $path.Substring($path.IndexOf("Pictures"))
    $lines.Add('    "' + $rel + '",')
  }

  $lines.Add("  ],")
}

$lines.Add("};")
$lines.Add("")
$lines.Add("export default galleryManifest;")

Set-Content -LiteralPath "gallery-manifest.js" -Value ($lines -join "`r`n") -Encoding UTF8
Write-Host "Updated gallery-manifest.js"
